// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-laptops.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
function env(k) {
  if (typeof Deno !== "undefined") return Deno.env.get(k);
  const p = globalThis.process;
  return p?.env?.[k];
}
function sb() {
  const url = env("SUPABASE_URL");
  const key = env("SUPABASE_PUBLISHABLE_KEY") ?? env("SUPABASE_ANON_KEY");
  if (!url || !key) throw new Error("Supabase env not configured");
  return createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-laptops.ts
var list_laptops_default = defineTool({
  name: "list_laptops",
  title: "List laptops",
  description: "List laptops available for rent at TeknoKerja Bali. Returns name, brand, specs, daily/weekly/monthly prices (IDR), and status.",
  inputSchema: {
    status: z.enum(["ready", "rented", "maintenance", "any"]).default("ready").describe("Filter by availability status. Default 'ready' = bookable now."),
    limit: z.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }) => {
    let q = sb().from("laptops").select("id,name,brand,processor,ram,ssd,vga,screen_size,price_daily,price_weekly,price_monthly,status,photo_url,notes").order("sort_order", { ascending: true }).limit(limit);
    if (status !== "any") q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { laptops: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-laptop.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_laptop_default = defineTool2({
  name: "get_laptop",
  title: "Get laptop details",
  description: "Fetch full details for a single laptop by its id, including gallery images and pricing.",
  inputSchema: {
    id: z2.string().uuid().describe("Laptop id (UUID) from list_laptops.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const { data, error } = await sb().from("laptops").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Laptop not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { laptop: data }
    };
  }
});

// src/lib/mcp/tools/list-articles.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_articles_default = defineTool3({
  name: "list_articles",
  title: "List blog articles",
  description: "List published blog articles from TeknoKerja. Filter by locale (en/id/ru/zh).",
  inputSchema: {
    locale: z3.enum(["en", "id", "ru", "zh"]).optional().describe("Language filter."),
    limit: z3.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ locale, limit }) => {
    let q = sb().from("articles").select("id,slug,title,excerpt,locale,tags,published_at,featured_image").eq("status", "published").order("published_at", { ascending: false }).limit(limit);
    if (locale) q = q.eq("locale", locale);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { articles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-article.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
var get_article_default = defineTool4({
  name: "get_article",
  title: "Get article by slug",
  description: "Fetch a published blog article by its slug (and optional locale).",
  inputSchema: {
    slug: z4.string().min(1).describe("Article slug, e.g. 'sewa-laptop-bali'."),
    locale: z4.enum(["en", "id", "ru", "zh"]).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug, locale }) => {
    let q = sb().from("articles").select("*").eq("slug", slug).eq("status", "published").limit(1);
    if (locale) q = q.eq("locale", locale);
    const { data, error } = await q.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Article not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { article: data }
    };
  }
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_contact_info_default = defineTool5({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Return TeknoKerja's public contact details (WhatsApp, email, address, hours) and website settings.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const { data, error } = await sb().from("website_settings").select("*").limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const info = {
      whatsapp: "+62 838-9108-8084",
      whatsapp_link: "https://wa.me/6283891088084",
      email: "iklansatu7@gmail.com",
      address: "Jl. Tukad Yeh Biu No.29, Sesetan, Denpasar Selatan, Bali 80225",
      hours: "Mon\u2013Fri 09:00\u201318:00, Sat 09:00\u201314:00 (WITA)",
      website: "https://teknokerja.com",
      settings: data ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "teknokerja-mcp",
  title: "TeknoKerja Bali \u2014 Laptop Rental",
  version: "0.1.0",
  instructions: "Tools for TeknoKerja, a laptop rental service in Bali. Use `list_laptops` to browse the current rental inventory (daily/weekly/monthly IDR pricing), `get_laptop` for full specs of one unit, `list_articles`/`get_article` for blog content in English/Indonesian/Russian/Chinese, and `get_contact_info` for WhatsApp and address. All tools are read-only.",
  tools: [list_laptops_default, get_laptop_default, list_articles_default, get_article_default, get_contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
